apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-agent
  template:
    metadata:
      labels:
        app: gemini-agent
    spec:
      containers:
        - name: gemini-agent
          image: gemini-agent:prod          # built or loaded into minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secrets
                  key: GOOGLE_API_KEY
            - name: GEMINI_MODEL
              value: gemini-2.5-flash
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3          # integers, not strings
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
